### PR TITLE
Change office info location

### PR DESCRIPTION
**Pull request by KilinMikhail**
Resolves https://github.com/fs/flatstack-warsaw/issues/61

1. removed Russia
2. renamed Kazan office to Global Office
3. added Turkey office
4. changed "live in Europe" → "... live in Europe or Turkey"
5. changed "to Warsaw" →" to Warsaw/Turkey"
6. updated Warsaw image

image
image

### CODE REVIEW

**Review by DanilAgafonov — COMMENTED** [review]
I have 3 comments:
1. Phrase "Global office" doesn't make any sense to me. What is strange is that it has photo. I don't get it. How something global can have photo?
2. Size of photos looks a bit bloated. Maybe we can compress them? Probably you already did it, but I can recommend https://squoosh.app/. It would be nice to try different params/options to achieve smallest possible size for all files
3. We need to change layout for sure. It doesn't look good. We can try 2x2 instead of current 1x3+1

**Review by DanilAgafonov — COMMENTED** [review]
@KilinMikhail 

And we need to think about "Fullstack developer to Warsaw/Turkey". The fact we write city and country in one line causes dissonance.

Please ask Zee to schedule a call. It is hard to discuss such massive changes in PR comments.

**Comment by KilinMikhail** [comment]
@DanilAgafonov Global office is from doc. What can I name it different? This name used to not use Kazan, Russia words. I can just remove kazan office from this page.

**Comment by DanilAgafonov** [comment]
> Global office is from doc

Which doc? Never seen any doc.

Can we have a call? Me, you, Zee and anybody else who prepared that doc.

**Comment by KilinMikhail** [comment]
> > Global office is from doc
> 
> Which doc? Never seen any doc.
> 
> Can we have a call? Me, you, Zee and anybody else who prepared that doc.

Ok, I sent message to Zee

**Comment by KilinMikhail** [comment]
> > > Global office is from doc
> > 
> > 
> > Which doc? Never seen any doc.
> > Can we have a call? Me, you, Zee and anybody else who prepared that doc.
> 
> Ok, I sent message to Zee

She will plan a call for tomorrow

**Review by DanilAgafonov — COMMENTED** [review]
For me photos looks distorted (broken aspect ration). Do you see it?

**Comment by KilinMikhail** [comment]
> For me photos looks distorted (broken aspect ration). Do you see it?

I will try to use another service to prepare them, sorry

**Comment by DanilAgafonov** [comment]
> > For me photos looks distorted (broken aspect ration). Do you see it?
> 
> I will try to use another service to prepare them, sorry

First of all you need to prepare original photo and make it the same aspect ratio as old photos. Then you can convert/compress it using https://squoosh.app/

**Review by DanilAgafonov — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
